import type { MessageKey } from "./keys.js";

export const de: Record<MessageKey, string> = {
	"command.register.description": "Registriere dein Riot-Konto und aktualisiere deinen Server-Nickname.",
	"command.register.name": "Dein persönlicher Name, wenn er im Nickname sichtbar sein soll.",
	"command.register.opgg": "Der Link zu deinem League-of-Legends-Profil auf OP.GG.",
	"command.register.hideName": "Verbirgt deinen persönlichen Namen im Discord-Nickname.",
	"command.registerUser.description": "Registriert ein Mitglied im Auftrag der Administration.",
	"command.registerUser.overrideDuplicate": "Erlaubt administrativ eine doppelte Riot-Kontozuordnung.",
	"command.member": "Das betroffene Servermitglied.",
	"command.setup.description": "Zeigt oder steuert die bestehende Registrierungsmigration.",
	"command.setup.mode": "Wählt eine Aktion für die Registrierungsmigration.",
	"command.setup.preview": "Vorschau",
	"command.setup.apply": "Anwenden",
	"command.setup.pause": "Pausieren",
	"command.setup.resume": "Fortsetzen",
	"command.setup.cancel": "Abbrechen",
	"command.setup.unknown": "Unbekannte Formate",
	"command.setup.status": "Status",
	"command.unregister.description": "Setzt ein Mitglied auf nicht registriert zurück.",
	"command.info.description": "Zeigt den Registrierungsstatus eines Mitglieds.",
	"command.syncNickname.description": "Gleicht Rollen und Nickname eines Mitglieds ab.",
	"command.syncRiot.description": "Aktualisiert die Riot-Identität eines Mitglieds.",
	"command.delete.description": "Löscht gespeicherte Registrierungsdaten eines Mitglieds.",
	"command.reconcile.description": "Repariert Rollen und Nickname anhand der Datenbank.",
	"registration.success": "Registrierung erfolgreich. Deine Discord-Rollen und dein Nickname wurden aktualisiert.",
	"registration.hiddenSuccess": "Registrierung erfolgreich. Dein Nickname zeigt ? | gefolgt von deiner Riot-ID.",
	"registration.invalidOpggUrl": "Der OP.GG-Link ist ungültig. Verwende einen vollständigen League-of-Legends-Profillink von op.gg.",
	"registration.riotAccountNotFound": "Dein Riot-Konto konnte nicht gefunden werden. Prüfe bitte den Riot-Namen, den Tag und den OP.GG-Link.",
	"registration.nameRequired": "Bitte gib einen nicht leeren persönlichen Namen an, wenn dein Name sichtbar sein soll.",
	"registration.nameNotAllowedWhenHidden": "Wenn du deinen Namen verbergen möchtest, darfst du keinen Namen angeben.",
	"registration.discordSyncPending":
		"Deine Registrierung wurde gespeichert. Dein Discord-Nickname oder deine Rollen konnten jedoch noch nicht vollständig aktualisiert werden. Der Bot versucht es automatisch erneut.",
	"registration.riotUnavailable": "Die Riot-Verifizierung ist derzeit nicht verfügbar. Bitte versuche es später erneut.",
	"registration.duplicatePuuid": "Dieses Riot-Konto ist auf diesem Server bereits registriert.",
	"registration.notInGuild": "Dieser Befehl kann nur auf dem konfigurierten Server verwendet werden.",
	"registration.botNotAllowed": "Bot-Konten können nicht registriert werden.",
	"registration.deleted": "Die gespeicherten Registrierungsdaten wurden gelöscht. Das Mitglied ist jetzt nicht registriert.",
	"registration.unregistered": "Das Mitglied wurde als nicht registriert markiert.",
	"migration.previewTitle": "Registrierungsmigration – Vorschau",
	"migration.previewBody": "Diese Aktion verarbeitet {total} Mitglieder und kann Nicknames, Rollen und Registrierungsstatus ändern.",
	"migration.confirmButton": "Migration anwenden",
	"migration.cancelButton": "Abbrechen",
	"migration.confirmed": "Die Migration wurde bestätigt und wird im Hintergrund verarbeitet.",
	"migration.paused": "Die Migration wurde pausiert. Ein bereits begonnenes Mitglied kann noch fertig verarbeitet werden.",
	"migration.cancelled": "Die Migration wurde abgebrochen.",
	"migration.activeCancelled":
		"Die aktive Migration wurde abgebrochen. Bereits verarbeitete Mitglieder wurden nicht zurückgesetzt. Du kannst jetzt eine neue Vorschau erstellen.",
	"migration.noPreview": "Es gibt keine gültige, noch nicht abgelaufene Migrationsvorschau.",
	"migration.activeExists": "Es gibt bereits eine laufende oder pausierte Migration. Prüfe zuerst ihren Status oder setze sie fort.",
	"migration.noActive": "Es gibt keine laufende oder pausierte Migration, die abgebrochen werden kann.",
	"migration.notRunning": "Es gibt keine laufende Migration, die pausiert werden kann.",
	"migration.notPaused": "Es gibt keine pausierte Migration, die fortgesetzt werden kann.",
	"migration.status": "Migrationsstatus: {status}. Verarbeitet: {processed}/{total}. Offen insgesamt: {pending}. Davon manuelle Prüfung: {manual}. Fehler: {failed}.",
	"migration.pendingRiotVerification": "Die Riot-Verifizierung ist vorübergehend ausstehend. Das Mitglied wird nicht automatisch entfernt.",
	"migration.unknownTitle": "Mitglieder mit unbekanntem Nickname-Format",
	"migration.unknownPage": "Seite {page}/{pages} · Insgesamt {total} Mitglieder",
	"migration.unknownEntry": "{username} ({userId}): {nickname}",
	"migration.unknownEmpty": "Diese Migrationsvorschau enthält keine Mitglieder mit unbekanntem Nickname-Format.",
	"migration.noNickname": "Kein Server-Nickname",
	"cleanup.removalDm": "Du bist seit sieben Tagen nicht registriert und wirst deshalb automatisch vom Server entfernt.",
	"cleanup.removalReason": "Seit sieben Tagen nicht registriert.",
	"permissions.denied": "Du hast keine Berechtigung für diesen Befehl.",
	"permissions.missingManageNicknames": "Dem Bot fehlt die Berechtigung „Nicknames verwalten“.",
	"permissions.memberNotManageable": "Dieses Mitglied kann wegen der Rollenreihenfolge nicht verwaltet werden.",
	"permissions.roleMissing": "Eine konfigurierte Registrierungsrolle wurde nicht gefunden: {role}.",
	"permissions.roleOrder": "Die Rollenreihenfolge ist ungültig: {detail}.",
	"permissions.roleHoist": "Die separate Anzeige der Rolle „{role}“ ist falsch konfiguriert.",
	"permissions.roleMentionable": "Die Erwähnbarkeit der Rolle „{role}“ entspricht nicht der Konfiguration.",
	"permissions.roleAdministrator": "Die Rolle „{role}“ darf keine Administratorberechtigung besitzen.",
	"permissions.intentMissing": "Der privilegierte „Server Members Intent“ ist nicht aktiviert.",
	"permissions.missingViewAuditLog": "Dem Bot fehlt die Berechtigung „Audit-Log anzeigen“, die für sichere administrative Nickname-Änderungen benötigt wird.",
	"common.unexpectedError": "Es ist ein unerwarteter Fehler aufgetreten. Bitte versuche es später erneut.",
	"common.riotTemporarilyUnavailable": "Riot ist vorübergehend nicht erreichbar. Deine bestehende Registrierung bleibt unverändert.",
	"common.syncSucceeded": "Rollen und Nickname wurden erfolgreich abgeglichen.",
	"common.syncPending": "Der Abgleich wurde gespeichert und wird automatisch erneut versucht.",
	"info.title": "Registrierungsinformationen",
	"info.body":
		"Discord-ID: {userId}\nDiscord-Benutzername: {username}\nStatus: {status}\nPersönlicher Name: {displayName}\nNamensanzeige: {visibility}\nRiot-ID: {riotId}\nPUUID: {puuid}\nPlattform: {platform}\nRegistriert am: {registeredAt}\nNicht registriert seit: {unregisteredSince}\nLetzte Riot-Aktualisierung: {lastSync}\nNächste Riot-Aktualisierung: {nextSync}\nRollensynchronisierung: {roleSync}\nNickname-Synchronisierung: {nicknameSync}\nMigrationsquelle: {migrationSource}\nLetzter Fehler: {lastFailure}",
	"sync.notRequired": "Nicht erforderlich",
	"sync.pending": "Ausstehend",
	"sync.inProgress": "Wird ausgeführt",
	"sync.succeeded": "Erfolgreich",
	"sync.retryable": "Fehlgeschlagen, erneuter Versuch geplant",
	"sync.permanent": "Dauerhaft fehlgeschlagen",
	"info.failurePresent": "Synchronisierung fehlgeschlagen; technische Details stehen im Protokoll.",
	"info.migrationLegacy": "Bestehender Server-Nickname",
	"audit.reconciliationReason": "Registrierungsstatus synchronisiert",
	"button.confirmDelete": "Daten löschen",
	"button.cancel": "Abbrechen",
	"button.previous": "Zurück",
	"button.next": "Weiter",
	"confirmation.deleteRegistrationData": "Möchtest du die gespeicherten Registrierungsdaten wirklich löschen?",
	"status.registered": "Registriert",
	"status.verifiedNoRiot": "Verifiziert ohne aktuelles Riot-Konto",
	"status.unregistered": "Nicht registriert",
	"status.pending": "Verifizierung ausstehend",
	"visibility.visible": "Sichtbar",
	"visibility.hidden": "Verborgen",
	"migration.category.visible": "Registriert mit sichtbarem Namen",
	"migration.category.hidden": "Registriert mit verborgenem Namen",
	"migration.category.verifiedNoRiot": "Verifiziert ohne aktuelles Riot-Konto",
	"migration.category.unregistered": "Nicht registriert",
	"migration.category.unknown": "Unbekanntes Format",
	"migration.category.unmanageable": "Nicht verwaltbar",
	"migration.category.exempt": "Ausgenommen",
	"migration.category.pending": "Riot-Verifizierung ausstehend",
	"migration.state.previewed": "Vorschau erstellt",
	"migration.state.running": "Wird ausgeführt",
	"migration.state.paused": "Pausiert",
	"migration.state.completed": "Abgeschlossen",
	"migration.state.cancelled": "Abgebrochen",
};
