import type { MessageKey } from "./keys.js";

export const de: Record<MessageKey, string> = {
	"command.register.description": "Registriere dein Riot-Konto und aktualisiere deinen Server-Nickname.",
	"command.register.name": "Dein persönlicher Name, wenn er im Nickname sichtbar sein soll.",
	"command.register.opgg": "Der Link zu deinem League-of-Legends-Profil auf OP.GG.",
	"command.register.hideName": "Verbirgt deinen persönlichen Namen im Discord-Nickname.",
	"command.registerUser.description": "Registriert ein Mitglied im Auftrag der Administration.",
	"command.contextRegister.name": "Mitglied registrieren",
	"modal.register.title": "Mitglied registrieren",
	"modal.register.riotAccountLabel": "Riot-ID oder OP.GG-Link",
	"modal.register.riotAccountPlaceholder": "Beispiel: RUS Yasuicide#777",
	"modal.register.nameLabel": "Persönlicher Name",
	"modal.register.namePlaceholder": "Leer lassen, wenn der Name privat bleibt",
	"modal.register.visibilityLabel": "Namensanzeige",
	"modal.register.visibilityPlaceholder": "sichtbar oder privat",
	"modal.register.visibilityDefault": "sichtbar",
	"modal.register.platformLabel": "League-Region",
	"modal.register.platformPlaceholder": "Beispiel: EUW, EUNE oder NA",
	"command.registerUser.overrideDuplicate": "Erlaubt administrativ eine doppelte Riot-Kontozuordnung.",
	"command.member": "Das betroffene Servermitglied.",
	"command.setup.description": "Zeigt oder steuert die bestehende Registrierungsmigration.",
	"command.setup.mode": "Wählt eine Aktion für die Registrierungsmigration.",
	"command.setup.preview": "Vorschau",
	"command.setup.apply": "Anwenden",
	"command.setup.pause": "Pausieren",
	"command.setup.resume": "Fortsetzen",
	"command.setup.cancel": "Abbrechen",
	"command.setup.unknown": "Unbekannte Formate",
	"command.setup.manualReview": "Manuelle Prüfungen",
	"command.setup.resolveReview": "Manuelle Regeln anwenden",
	"command.setup.status": "Status",
	"command.unregister.description": "Setzt ein Mitglied auf nicht registriert zurück.",
	"command.info.description": "Zeigt den Registrierungsstatus eines Mitglieds.",
	"command.syncNickname.description": "Gleicht Rollen und Nickname eines Mitglieds ab.",
	"command.syncRiot.description": "Aktualisiert die Riot-Identität eines Mitglieds.",
	"command.delete.description": "Löscht gespeicherte Registrierungsdaten eines Mitglieds.",
	"command.reconcile.description": "Repariert Rollen und Nickname anhand der Datenbank.",
	"command.league.description": "Zeigt League-Ränge und Champion-Mastery auf diesem Server.",
	"command.league.profile": "Zeigt das League-Profil eines Mitglieds.",
	"command.league.mastery": "Zeigt die höchsten Champion-Mastery-Werte eines Mitglieds.",
	"command.league.chart": "Erstellt ein Diagramm zur Mastery-Entwicklung.",
	"command.league.top": "Zeigt die Mastery-Bestenliste dieses Servers.",
	"command.league.refresh": "Aktualisiert League-Rang, Mastery und Rangrolle.",
	"command.league.roles": "Zeigt den gespeicherten Rang und die erwartete Rangrolle.",
	"command.league.help": "Erklärt die League-Befehle.",
	"command.league.about": "Zeigt Informationen zur League-Erweiterung.",
	"command.league.member": "Das Mitglied; ohne Angabe wird dein eigenes Profil verwendet.",
	"command.league.champion": "Championname oder numerische Champion-ID.",
	"command.league.topType": "Wählt die Bestenliste aus.",
	"command.league.topTotal": "Gesamt-Mastery",
	"command.league.topChampion": "Champion-Mastery",
	"league.notRegistered": "Dieses Mitglied hat kein registriertes Riot-Konto.",
	"league.noData": "Für dieses Mitglied liegen noch keine League-Daten vor. Verwende zuerst `/league refresh`.",
	"league.profileTitle": "League-Profil · {riotId}",
	"league.profileBody":
		"Level: **{level}**\nSolo/Duo: **{solo}**\nFlex: **{flex}**\nHöchster Rang ohne TFT: **{effective}**\nGesamt-Mastery: **{mastery}**\nZuletzt aktualisiert: {updated}",
	"league.masteryTitle": "Champion-Mastery · {riotId}",
	"league.masteryEntry": "**{position}. {champion}** · Stufe {level} · {points} Punkte",
	"league.chartTitle": "Mastery-Entwicklung · {champion}",
	"league.topTitle": "Server-Bestenliste · {category}",
	"league.refreshSuccess": "League-Rang, Mastery und Rangrolle wurden aktualisiert.",
	"league.refreshFailed": "Die League-Daten konnten gerade nicht aktualisiert werden. Bestehende Daten und Rollen bleiben erhalten.",
	"league.rolesTitle": "League-Rangrolle · {riotId}",
	"league.rolesBody": "Berücksichtigter Rang: **{rank}**\nErwartete Rolle: **{role}**\nTFT wird bei Rangrollen nicht berücksichtigt.",
	"league.helpTitle": "League-Befehle",
	"league.helpBody":
		"`/league profile` – Profil und Ränge\n`/league mastery` – beste Champions\n`/league chart` – Mastery-Verlauf\n`/league top` – Server-Bestenlisten\n`/league refresh` – Daten und Rangrolle aktualisieren\n`/league roles` – Rangrollenstatus",
	"league.mentionHelpTitle": "League-Hilfe",
	"league.mentionHelpBody":
		"Was möchtest du ansehen?\n\n`@Bot profil` – dein League-Profil und deine Ränge\n`@Bot mastery` – deine stärksten Champions\n`@Bot top Ahri` – die Server-Bestenliste für einen Champion\n\nAlle Funktionen und weitere Optionen findest du unter `/league help`.",
	"league.aboutTitle": "League-Funktionen",
	"league.aboutBody":
		"Der Bot verwendet dein über `/register` verknüpftes Riot-Konto. Rangrollen basieren ausschließlich auf dem höheren Rang aus Solo/Duo und Flex; TFT ist ausgeschlossen. Mastery-Verläufe beginnen mit dem ersten gespeicherten Snapshot.",
	"league.championNotFound": "Dieser Champion wurde nicht gefunden. Prüfe bitte den Namen oder verwende die numerische Champion-ID.",
	"league.historyInsufficient": "Für diesen Champion gibt es noch nicht genügend Snapshots für ein Verlaufsdiagramm.",
	"league.joinDm":
		"Willkommen auf **{server}**! Registriere dein Riot-Konto mit `/register`. Danach hält der Bot deinen Server-Nickname, deine Registrierungsrolle, deinen League-Rang und deine Champion-Mastery aktuell. Falls du Hilfe brauchst, verwende `/league help`.",
	"league.rankUnranked": "Ohne Rang",
	"league.rankRoleDisabled": "Rangrollen sind nicht aktiviert",
	"league.rankLabel": "{tier}{division} · {lp} LP",
	"league.topEntry": "**{position}.** <@{userId}> · {points} Punkte",
	"rank.IRON": "Eisen",
	"rank.BRONZE": "Bronze",
	"rank.SILVER": "Silber",
	"rank.GOLD": "Gold",
	"rank.PLATINUM": "Platin",
	"rank.EMERALD": "Smaragd",
	"rank.DIAMOND": "Diamant",
	"rank.MASTER": "Meister",
	"rank.GRANDMASTER": "Großmeister",
	"rank.CHALLENGER": "Herausforderer",
	"registration.success": "Registrierung erfolgreich. Deine Discord-Rollen und dein Nickname wurden aktualisiert.",
	"registration.hiddenSuccess": "Registrierung erfolgreich. Dein Nickname zeigt ? | gefolgt von deiner Riot-ID.",
	"registration.invalidOpggUrl": "Der OP.GG-Link ist ungültig. Verwende einen vollständigen League-of-Legends-Profillink von op.gg.",
	"registration.invalidRiotId": "Die Riot-ID ist ungültig. Verwende das Format RiotName#TAG.",
	"registration.invalidPlatform": "Die League-Region ist ungültig. Verwende zum Beispiel EUW, EUNE, NA, KR oder TR.",
	"registration.invalidVisibility": "Die Namensanzeige ist ungültig. Gib sichtbar oder privat ein.",
	"registration.riotAccountNotFound": "Dein Riot-Konto konnte nicht gefunden werden. Prüfe bitte den Riot-Namen, den Tag und den OP.GG-Link.",
	"registration.nameRequired": "Bitte gib einen nicht leeren persönlichen Namen an, wenn dein Name sichtbar sein soll.",
	"registration.nameNotAllowedWhenHidden": "Wenn du deinen Namen verbergen möchtest, darfst du keinen Namen angeben.",
	"registration.discordSyncPending":
		"Deine Registrierung wurde gespeichert. Dein Discord-Nickname oder deine Rollen konnten jedoch noch nicht vollständig aktualisiert werden. Der Bot versucht es automatisch erneut.",
	"registration.riotUnavailable": "Die Riot-Verifizierung ist derzeit nicht verfügbar. Bitte versuche es später erneut.",
	"registration.duplicatePuuid": "Dieses Riot-Konto ist auf diesem Server bereits registriert.",
	"registration.duplicateRequiresAdministrator": "Dieses Riot-Konto ist bereits registriert. Nur ein Administrator darf es als Zweitkonto verknüpfen.",
	"registration.staffModalSuccess": "Das Mitglied wurde erfolgreich registriert. Discord-Rollen und Nickname wurden aktualisiert.",
	"registration.notInGuild": "Dieser Befehl kann nur auf dem konfigurierten Server verwendet werden.",
	"registration.botNotAllowed": "Bot-Konten können nicht registriert werden.",
	"registration.deleted": "Die gespeicherten Registrierungsdaten wurden gelöscht. Das Mitglied ist jetzt nicht registriert.",
	"registration.unregistered": "Das Mitglied wurde als nicht registriert markiert.",
	"migration.previewTitle": "Registrierungsmigration – Vorschau",
	"migration.previewBody": "Diese Aktion verarbeitet {total} Mitglieder und kann Nicknames, Rollen und Registrierungsstatus ändern.",
	"migration.confirmButton": "Migration anwenden",
	"migration.cancelButton": "Abbrechen",
	"migration.confirmed": "Die Migration wurde bestätigt und wird im Hintergrund verarbeitet.",
	"migration.paused": "Die Migration wurde pausiert. Ein bereits begonnenes Mitglied kann noch fertig verarbeitet werden.",
	"migration.cancelled": "Die Migration wurde abgebrochen.",
	"migration.activeCancelled":
		"Die aktive Migration wurde abgebrochen. Bereits verarbeitete Mitglieder wurden nicht zurückgesetzt. Du kannst jetzt eine neue Vorschau erstellen.",
	"migration.noPreview": "Es gibt keine gültige, noch nicht abgelaufene Migrationsvorschau.",
	"migration.activeExists": "Es gibt bereits eine laufende oder pausierte Migration. Prüfe zuerst ihren Status oder setze sie fort.",
	"migration.noActive": "Es gibt keine laufende oder pausierte Migration, die abgebrochen werden kann.",
	"migration.notRunning": "Es gibt keine laufende Migration, die pausiert werden kann.",
	"migration.notPaused": "Es gibt keine pausierte Migration, die fortgesetzt werden kann.",
	"migration.status": "Migrationsstatus: {status}. Verarbeitet: {processed}/{total}. Offen insgesamt: {pending}. Davon manuelle Prüfung: {manual}. Fehler: {failed}.",
	"migration.statusTitle": "Registrierungsmigration – Status",
	"migration.progressLine": "`{bar}` **{percent} %**",
	"migration.statusFieldState": "Status",
	"migration.statusFieldProcessed": "Verarbeitet",
	"migration.statusFieldRemaining": "Noch offen",
	"migration.statusFieldVerified": "Verifiziert",
	"migration.statusFieldUnregistered": "Nicht registriert",
	"migration.statusFieldManual": "Manuelle Prüfung",
	"migration.statusFieldPendingRetry": "Wiederholung ausstehend",
	"migration.statusFieldFailed": "Fehler",
	"migration.statusLiveFooter": "Automatische Aktualisierung alle 30 Sekunden für bis zu 14 Minuten",
	"migration.statusStaticFooter": "Mit „Aktualisieren“ kannst du den aktuellen Stand neu laden.",
	"migration.refreshButton": "Aktualisieren",
	"migration.manualReviewButton": "Manuelle Prüfungen ({count})",
	"migration.backToStatusButton": "Zurück zum Status",
	"migration.manualReviewTitle": "Mitglieder zur manuellen Prüfung",
	"migration.manualReviewPage": "Seite {page}/{pages} · Insgesamt {total} Mitglieder",
	"migration.manualReviewEmpty": "Für diese Migration gibt es derzeit keine Mitglieder zur manuellen Prüfung.",
	"migration.manualReviewEntry": "Nickname: {nickname}\nGrund: {reason}\nKonflikt mit: {conflict}",
	"migration.manualReviewNoConflict": "–",
	"migration.manualReasonDuplicate": "Das Riot-Konto ist bereits einem anderen Discord-Mitglied zugeordnet.",
	"migration.manualReasonRiotNotFound": "Das private Riot-Konto konnte nicht gefunden werden.",
	"migration.manualReasonUnknownFormat": "Das ursprüngliche Nickname-Format konnte nicht eindeutig zugeordnet werden.",
	"migration.manualReasonOther": "Der Fall konnte nicht automatisch entschieden werden.",
	"migration.reviewPreviewTitle": "Manuelle Fälle erneut verarbeiten",
	"migration.reviewPreviewBody":
		"Diese Aktion verarbeitet {total} bisher offene Fälle erneut. Unbekannte Formate und nicht gefundene private Riot-IDs werden als nicht registriert eingestuft. Doppelte Riot-Konten übernehmen Name, Sichtbarkeit und Riot-Identität des zuerst registrierten Discord-Kontos.",
	"migration.reviewNone": "Es gibt keine manuellen oder fehlgeschlagenen Migrationsfälle, die erneut verarbeitet werden können.",
	"migration.pendingRiotVerification": "Die Riot-Verifizierung ist vorübergehend ausstehend. Das Mitglied wird nicht automatisch entfernt.",
	"migration.unknownTitle": "Mitglieder mit unbekanntem Nickname-Format",
	"migration.unknownPage": "Seite {page}/{pages} · Insgesamt {total} Mitglieder",
	"migration.unknownEntry": "{username} ({userId}): {nickname}",
	"migration.unknownEmpty": "Diese Migrationsvorschau enthält keine Mitglieder mit unbekanntem Nickname-Format.",
	"migration.noNickname": "Kein Server-Nickname",
	"cleanup.removalDm": "Du bist seit sieben Tagen nicht registriert und wirst deshalb automatisch vom Server entfernt.",
	"cleanup.removalReason": "Seit sieben Tagen nicht registriert.",
	"permissions.denied": "Du hast keine Berechtigung für diesen Befehl.",
	"permissions.missingManageNicknames": "Dem Bot fehlt die Berechtigung „Nicknames verwalten“.",
	"permissions.memberNotManageable": "Dieses Mitglied kann wegen der Rollenreihenfolge nicht verwaltet werden.",
	"permissions.roleMissing": "Eine konfigurierte Registrierungsrolle wurde nicht gefunden: {role}.",
	"permissions.roleOrder": "Die Rollenreihenfolge ist ungültig: {detail}.",
	"permissions.roleHoist": "Die separate Anzeige der Rolle „{role}“ ist falsch konfiguriert.",
	"permissions.roleMentionable": "Die Erwähnbarkeit der Rolle „{role}“ entspricht nicht der Konfiguration.",
	"permissions.roleAdministrator": "Die Rolle „{role}“ darf keine Administratorberechtigung besitzen.",
	"permissions.intentMissing": "Der privilegierte „Server Members Intent“ ist nicht aktiviert.",
	"permissions.missingViewAuditLog": "Dem Bot fehlt die Berechtigung „Audit-Log anzeigen“, die für sichere administrative Nickname-Änderungen benötigt wird.",
	"common.unexpectedError": "Es ist ein unerwarteter Fehler aufgetreten. Bitte versuche es später erneut.",
	"common.riotTemporarilyUnavailable": "Riot ist vorübergehend nicht erreichbar. Deine bestehende Registrierung bleibt unverändert.",
	"common.syncSucceeded": "Rollen und Nickname wurden erfolgreich abgeglichen.",
	"common.syncPending": "Der Abgleich wurde gespeichert und wird automatisch erneut versucht.",
	"info.title": "Registrierungsinformationen",
	"info.body":
		"Discord-ID: {userId}\nDiscord-Benutzername: {username}\nStatus: {status}\nPersönlicher Name: {displayName}\nNamensanzeige: {visibility}\nRiot-ID: {riotId}\nPUUID: {puuid}\nPlattform: {platform}\nRegistriert am: {registeredAt}\nNicht registriert seit: {unregisteredSince}\nLetzte Riot-Aktualisierung: {lastSync}\nNächste Riot-Aktualisierung: {nextSync}\nRollensynchronisierung: {roleSync}\nNickname-Synchronisierung: {nicknameSync}\nMigrationsquelle: {migrationSource}\nLetzter Fehler: {lastFailure}",
	"sync.notRequired": "Nicht erforderlich",
	"sync.pending": "Ausstehend",
	"sync.inProgress": "Wird ausgeführt",
	"sync.succeeded": "Erfolgreich",
	"sync.retryable": "Fehlgeschlagen, erneuter Versuch geplant",
	"sync.permanent": "Dauerhaft fehlgeschlagen",
	"info.failurePresent": "Synchronisierung fehlgeschlagen; technische Details stehen im Protokoll.",
	"info.migrationLegacy": "Bestehender Server-Nickname",
	"audit.reconciliationReason": "Registrierungsstatus synchronisiert",
	"audit.rankReconciliationReason": "League-Rang synchronisiert",
	"auditLog.title.roleUpdate": "Mitgliederrollen aktualisiert",
	"auditLog.title.nicknameUpdate": "Server-Nickname aktualisiert",
	"auditLog.title.registration": "Registrierung aktualisiert",
	"auditLog.title.memberLifecycle": "Mitgliedsstatus aktualisiert",
	"auditLog.title.cleanup": "Automatische Bereinigung",
	"auditLog.title.migration": "Registrierungsmigration",
	"auditLog.title.administrativeNickname": "Administrative Nickname-Änderung",
	"auditLog.title.dataProtection": "Registrierungsdaten gelöscht",
	"auditLog.title.generic": "Bot-Aktion protokolliert",
	"auditLog.field.member": "Mitglied",
	"auditLog.field.actor": "Ausgeführt von",
	"auditLog.field.added": "Hinzugefügt",
	"auditLog.field.removed": "Entfernt",
	"auditLog.field.reason": "Grund",
	"auditLog.field.result": "Ergebnis",
	"auditLog.actor.automatic": "Automatisch",
	"auditLog.reason.registrationSync": "Registrierungsrolle synchronisiert",
	"auditLog.reason.rankSync": "League-Rang synchronisiert",
	"auditLog.reason.nicknameSync": "Registrierungsnickname synchronisiert",
	"auditLog.reason.registration": "Registrierung verarbeitet",
	"auditLog.reason.memberLifecycle": "Serverbeitritt oder Serveraustritt verarbeitet",
	"auditLog.reason.cleanup": "Regel für nicht registrierte Mitglieder verarbeitet",
	"auditLog.reason.migration": "Registrierungsmigration verarbeitet",
	"auditLog.reason.administrativeNickname": "Administrative Nickname-Änderung verarbeitet",
	"auditLog.reason.dataProtection": "Gespeicherte personenbezogene Registrierungsdaten entfernt",
	"auditLog.reason.generic": "Automatische Bot-Aktion ausgeführt",
	"auditLog.result.success": "Erfolgreich",
	"auditLog.result.noop": "Keine Änderung erforderlich",
	"auditLog.result.pending": "Wiederholung ausstehend",
	"auditLog.result.started": "Gestartet",
	"auditLog.result.failed": "Fehlgeschlagen",
	"auditLog.footer": "GamingCommunity Bot · Auditprotokoll",
	"permissions.logWebhookInvalid": "Der konfigurierte Bot-Log-Webhook ist ungültig, wurde gelöscht oder gehört nicht zu diesem Server.",
	"permissions.logWebhookUnavailable": "Der Bot-Log-Webhook konnte vorübergehend nicht geprüft werden. Neue Protokolle werden gespeichert und später erneut gesendet.",
	"button.confirmDelete": "Daten löschen",
	"button.cancel": "Abbrechen",
	"button.previous": "Zurück",
	"button.next": "Weiter",
	"confirmation.deleteRegistrationData": "Möchtest du die gespeicherten Registrierungsdaten wirklich löschen?",
	"status.registered": "Registriert",
	"status.verifiedNoRiot": "Verifiziert ohne aktuelles Riot-Konto",
	"status.unregistered": "Nicht registriert",
	"status.pending": "Verifizierung ausstehend",
	"visibility.visible": "Sichtbar",
	"visibility.hidden": "Verborgen",
	"migration.category.visible": "Registriert mit sichtbarem Namen",
	"migration.category.hidden": "Registriert mit verborgenem Namen",
	"migration.category.verifiedNoRiot": "Verifiziert ohne aktuelles Riot-Konto",
	"migration.category.unregistered": "Nicht registriert",
	"migration.category.unknown": "Unbekanntes Format",
	"migration.category.unmanageable": "Nicht verwaltbar",
	"migration.category.exempt": "Ausgenommen",
	"migration.category.pending": "Riot-Verifizierung ausstehend",
	"migration.state.previewed": "Vorschau erstellt",
	"migration.state.running": "Wird ausgeführt",
	"migration.state.paused": "Pausiert",
	"migration.state.completed": "Abgeschlossen",
	"migration.state.cancelled": "Abgebrochen",
};
